In [41]:
import numpy as np
import pandas as pd

In [42]:
recommendation=pd.read_csv("in-vehicle-coupon-recommendation.csv")
recommendation.head()

,destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CoffeeHouse,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y
0,No Urgent Place,Alone,Sunny,55,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,never,NaN,4~8,1~3,1,0,0,0,1,1
1,No Urgent Place,Friend(s),Sunny,80,10AM,Coffee House,2h,Female,21,Unmarried partner,...,never,NaN,4~8,1~3,1,0,0,0,1,0
2,No Urgent Place,Friend(s),Sunny,80,10AM,Carry out & Take away,2h,Female,21,Unmarried partner,...,never,NaN,4~8,1~3,1,1,0,0,1,1
3,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,2h,Female,21,Unmarried partner,...,never,NaN,4~8,1~3,1,1,0,0,1,0
4,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,1d,Female,21,Unmarried partner,...,never,NaN,4~8,1~3,1,1,0,0,1,0

In [43]:
#Checking all columns how many na values are there
recommendation.isna().sum()

destination                 0
passanger                   0
weather                     0
temperature                 0
time                        0
coupon                      0
expiration                  0
gender                      0
age                         0
maritalStatus               0
has_children                0
education                   0
occupation                  0
income                      0
car                     12576
Bar                       107
CoffeeHouse               217
CarryAway                 151
RestaurantLessThan20      130
Restaurant20To50          189
toCoupon_GEQ5min            0
toCoupon_GEQ15min           0
toCoupon_GEQ25min           0
direction_same              0
direction_opp               0
Y                           0
dtype: int64

In [44]:
recommendation.nunique()

destination              3
passanger                4
weather                  3
temperature              3
time                     5
coupon                   5
expiration               2
gender                   2
age                      8
maritalStatus            5
has_children             2
education                6
occupation              25
income                   9
car                      5
Bar                      5
CoffeeHouse              5
CarryAway                5
RestaurantLessThan20     5
Restaurant20To50         5
toCoupon_GEQ5min         1
toCoupon_GEQ15min        2
toCoupon_GEQ25min        2
direction_same           2
direction_opp            2
Y                        2
dtype: int64

In [45]:
recommendation.shape

(12684, 26)

In [46]:
print(recommendation['car'].unique())

[nan 'Scooter and motorcycle' 'crossover' 'Mazda5' 'do not drive'
 'Car that is too old to install Onstar :D']

In [47]:
#I am dropping the cars columns as it doesn't have a value most of the times
recommendation.drop(['car'],axis='columns',inplace=True)

In [48]:
#Filling never for na values
recommendation['Bar']=recommendation['Bar'].fillna('never')

In [49]:
# print(recommendation['CoffeeHouse'].unique())
# print(recommendation['CarryAway'].unique())
# print(recommendation['RestaurantLessThan20'].unique())
# print(recommendation['Restaurant20To50'].unique())
columns_to_fill = ['CoffeeHouse', 'CarryAway', 'RestaurantLessThan20', 'Restaurant20To50']
for column in columns_to_fill:
    recommendation[column] = recommendation[column].fillna('never')

In [ ]:
recommendation.head() #Reduced all na columns

,destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CoffeeHouse,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y
0,1,0,2,55,2,4,0,0,0,3,...,4,4,1,0,1,0,0,0,1,1
1,1,1,2,80,0,2,1,0,0,3,...,4,4,1,0,1,0,0,0,1,0
2,1,1,2,80,0,1,1,0,0,3,...,4,4,1,0,1,1,0,0,1,1
3,1,1,2,80,2,2,1,0,0,3,...,4,4,1,0,1,1,0,0,1,0
4,1,1,2,80,2,2,0,0,0,3,...,4,4,1,0,1,1,0,0,1,0

In [51]:
from sklearn.preprocessing import LabelEncoder
lecol=['destination','passanger','weather','time','coupon','expiration','gender','age',
'maritalStatus','education','occupation','income','Bar','CoffeeHouse','CarryAway',
'RestaurantLessThan20','Restaurant20To50']
for col in recommendation[lecol]:
  le=LabelEncoder()
  recommendation[col]=le.fit_transform(recommendation[col])
# for col in lecol
#Using label encoding for objects